### ISSUE TITLE
The forced alignment file

### ISSUE THREAD

**Issue by cwghnu** [popcornell/OSDC#1]
Hello, can you share your forced alignment label file? And did you use the forced alignment label files provided in paper "LEVERAGING LSTM MODELS FOR OVERLAP DETECTION IN MULTI-PARTY MEETINGS"? Do you know the meaning of label -1,0,1,2? It is important for me. I would appreciate your answer. Thanks.

**Comment by popcornell** [comment]
Hi, my co-author Maurizio Omologo used the standard Kaldi AMI recipe to produce the alignments. 
I will ask him if it is possible to share them. I also think it is not too difficult to produce those by yourself using Kaldi. 
Treat -1, 0 as non-speech. 1 is single speaker 2 is overlap.

**Comment by popcornell** [comment]
Sorry for the late reply, i ve included the forced alignment annotation [onedrive-link]( https://univpm-my.sharepoint.com/:u:/g/personal/s1095350_pm_univpm_it/EXQzDQ8PYxVJjOGA2S6hELkBCU33L5WX32eIJ_xupUqXSQ?e=LyXrBk)

**Comment by cwghnu** [comment]
Thank you.
